# Generated by Django 5.0 on 2024-01-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
