# Generated by Django 5.0 on 2024-02-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('phonenumber', models.PositiveBigIntegerField()),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
