# Generated by Django 5.0 on 2024-02-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0006_rename_password_feedback_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpId', models.CharField(max_length=10, unique=True)),
                ('EmpName', models.CharField(max_length=100)),
                ('EmpGender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('EmpEmail', models.EmailField(max_length=254)),
                ('EmpDesignation', models.CharField(choices=[('Principal', 'Principal'), ('HOD', 'HOD'), ('Dean', 'Dean'), ('Web Developer', 'Web Developer'), ('Administrator Officer', 'Administrator Officer')], max_length=50)),
            ],
        ),
    ]
