# Generated by Django 5.0 on 2024-02-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0008_userprofile_delete_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
